# Generated by Django 4.2.4 on 2023-09-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmname', models.CharField(max_length=30)),
                ('star', models.CharField(max_length=30)),
                ('releaseDate', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=30)),
                ('directorName', models.CharField(max_length=30)),
            ],
        ),
    ]
