# Generated by Django 4.2.4 on 2023-09-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='filmname',
            new_name='filmName',
        ),
    ]
