# Generated by Django 4.2.4 on 2023-09-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
