# Generated by Django 4.2.4 on 2023-09-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_contactus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='reply',
            field=models.CharField(blank=True, default='no reply', max_length=30, null=True),
        ),
    ]
